eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 10

spring:
  application:
    name: GATEWAY


pring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
